spring:
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
              - TRACE
      routes:
        - id: course-service
          uri:
            ${COURSE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/course/**, /swagger/**
        - id: assessment-service-get
          uri: ${ASSESSMENT_BFF_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/assessment/**
            - Method=GET
          filters:
            - RewritePath=/assessment/, /bff/assessment/
            - name: AddResponseHeader # Add CORS header to the response
              args:
                name: Access-Control-Allow-Origin
                value: "http://localhost:4200"
        - id: assessment-service-post-put-delete
          uri: ${ASSESSMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/assessment/**
            - Method=POST,PUT,DELETE
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG