spring:
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - Authorization
              - Content-Type
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowCredentials: true
      routes:
        - id: course-service
          uri:
            ${COURSE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/course/**, /swagger/**
        - id: enrolment-service-get
          uri:
            ${COURSE_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/enrolment
            - Method=GET,OPTIONS
          filters:
            - RewritePath=/enrolment, /bff/enrolment

        - id: enrolment-service-get-with-parameter
          uri:
            ${COURSE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/enrolment/**
            - Method=GET,OPTIONS

        - id: enrolment-service-post-put-delete
          uri:
            ${COURSE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/enrolment/**, /swagger/**
            - Method=POST,PUT,PATCH,DELETE,OPTIONS

        - id: assessment-question-get
          uri:
            ${ASSESSMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/question/**, /swagger/**

        - id: assessment-service-get
          uri:
            ${ASSESSMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/assessment
            - Method=GET,OPTIONS
          filters:
#            - RewritePath=/(?<path>assessment|question)/?(?<segment>.*), /bff/$\{path}/$\{segment}
            - RewritePath=/assessment, /bff/assessment

        - id: assessment-service-get-with-student
          uri: ${ASSESSMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/assessment/student
            - Method=GET,OPTIONS
          filters:
            - RewritePath=/assessment/student, /bff/assessment/student

        - id: assessment-service-get-with-parameter
          uri:
            ${ASSESSMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/assessment/**
            - Method=GET,OPTIONS

        - id: assessment-service-post-put-delete
          uri:
            ${ASSESSMENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/assessment/**, /question/**
            - Method=POST,PUT,PATCH,DELETE,OPTIONS
        - id: ai-service
          uri:
            ${SCORE_AI_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/scoring/**, /swagger/**
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG