apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fetebird-gemini-hackathon
  namespace: fetebird-gemini-hackathon
spec:
  description: >-
    Clone a git repository. This example pipeline demonstrates the following:
    How to use the git-clone catalog Task
  params:
    - name: REPO_URL
      type: string
      description: The git repository URL to clone from.

  workspaces:
    - name: shared-data
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task for the repo's README.md file to be read.
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "$(params.REPO_URL)"
        - name: deleteExisting
          value: "true"