apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fetebird-gemini-hackathon-pvc
  namespace: fetebird-gemini-hackathon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
